const CART_ACTION_TYPES = {
    TOGGLE_DROPDOWN: 'TOGGLE_DROPDOWN',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART:'REMOVE_FROM_CART',
    CLEAR_PRODUCT_FROM_CART:'CLEAR_PRODUCT_FROM_CART',
    SET_CART_TOTAL:'SET_CART_TOTAL'
  };

export default CART_ACTION_TYPES